# Generated by Django 5.2.8 on 2026-05-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('login_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Login History',
                'verbose_name_plural': 'User Login Histories',
                'ordering': ['-login_at'],
            },
        ),
    ]
